# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpeciesExplorer
                                 A QGIS plugin
 Quickly fetch and visualise species occurrence data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-22
        copyright            : (C) 2018 by Kartoza
        email                : tim@kartoza.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import sys
import os
sys.path.append(os.path.dirname(__file__))


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SpeciesExplorer class from file SpeciesExplorer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from species_explorer.species_explorer import SpeciesExplorer
    return SpeciesExplorer(iface)
